import {verbs,vocabulary,grammar,speaking,writing} from "../data/curriculum.js";
const $=id=>document.getElementById(id);const KEY="yki-progress-v1";let progress=JSON.parse(localStorage.getItem(KEY)||"{}");let q=null,session={done:0,correct:0,total:10};
const shuffle=a=>[...a].sort(()=>Math.random()-.5),pick=a=>a[Math.floor(Math.random()*a.length)],norm=s=>(s||"").trim().toLowerCase().replace(/[.!?]+$/,"").replace(/\s+/g," ");
const items=[...vocabulary.map(data=>({kind:"vocab",data})),...verbs.map(data=>({kind:"verb",data})),...grammar.map(data=>({kind:"grammar",data})),...grammar.map(data=>({kind:"sentence",data})),...speaking.map(data=>({kind:"speaking",data})),...writing.map(data=>({kind:"writing",data}))];
[...new Set(items.map(x=>x.data.topic))].sort().forEach(t=>{const o=document.createElement("option");o.value=t;o.textContent=t;$( "topic").appendChild(o)});
function mastery(id){const x=progress[id];return x&&x.attempts?x.correct/x.attempts:0}function record(id,ok){const x=progress[id]||{attempts:0,correct:0};x.attempts++;if(ok)x.correct++;progress[id]=x;localStorage.setItem(KEY,JSON.stringify(progress))}
function make(filters){let pool=items.filter(x=>(filters.skill==="mixed"||({"vocab":"vocabulary","verb":"verbs","grammar":"grammar","sentence":"sentence","speaking":"speaking","writing":"writing"})[x.kind]===filters.skill)&&(filters.level==="all"||x.data.level===filters.level)&&(filters.topic==="all"||x.data.topic===filters.topic));if(!pool.length)pool=items.filter(x=>filters.level==="all"||x.data.level===filters.level);if(!pool.length)pool=items;const weighted=pool.flatMap(x=>Array(Math.max(1,Math.round((1-mastery(x.data.id))*5))).fill(x));const x=pick(weighted),d=x.data;
if(x.kind==="vocab"){const mode=pick(["mcq","text"]);if(mode==="mcq"){const opts=shuffle([d.swedish,...shuffle(vocabulary.filter(v=>v.id!==d.id)).slice(0,3).map(v=>v.swedish)]);return{id:d.id,type:"choice",skill:"Vocabulary",level:d.level,topic:d.topic,prompt:`What is the Swedish for “${d.english}”?`,options:opts,answer:d.swedish,explain:`${d.swedish} = ${d.english}`}}return{id:d.id,type:"text",skill:"Vocabulary",level:d.level,topic:d.topic,prompt:`Translate into English: “${d.swedish}”`,answer:d.english,explain:`${d.swedish} = ${d.english}`}}
if(x.kind==="verb"){const tense=pick(["present","past","supine"]),answer=d[tense],frame=tense==="present"?"Jag ___ varje dag.":tense==="past"?"Igår ___ jag.":"Jag har ___.";return{id:d.id,type:"text",skill:"Verbs",level:d.level,topic:d.topic,prompt:`Complete: “${frame}” — ${d.infinitive}`,answer,explain:`${d.infinitive}: ${d.present} / ${d.past} / har ${d.supine}`}}
if(x.kind==="grammar"){const sets={v2:["Choose the correct sentence:",["Idag vill jag inte köpa cykeln.","Idag jag vill inte köpa cykeln.","Idag vill inte jag köpa cykeln."],"Idag vill jag inte köpa cykeln."],biff:["Choose the correct subordinate clause:",["eftersom jag inte förstår frågan","eftersom jag förstår inte frågan"],"eftersom jag inte förstår frågan"],questions:["Choose the correct open question:",["Vad kostar den här varan?","Vad den här varan kostar?","Kostar vad den här varan?"],"Vad kostar den här varan?"],indirect:["Choose the correct indirect question:",["Jag vill veta om kontoret är öppet.","Jag vill veta om är kontoret öppet."],"Jag vill veta om kontoret är öppet."],enett:["Choose the definite form of “en bil”:",["bilen","bilet","bilar"],"bilen"],future:["Choose the form used for a plan:",["Jag ska resa imorgon.","Jag kommer att resa imorgon."],"Jag ska resa imorgon."],prep:["Choose the correct phrase:",["på måndag","i måndag","på måndags"],"på måndag"]};const [prompt,options,answer]=sets[d.id]||sets.v2;return{id:d.id,type:"choice",skill:"Grammar",level:d.level,topic:d.topic,prompt,options,answer,explain:d.explanation}}
if(x.kind==="sentence"){const e=pick([{words:["idag","ska","vi","handla"],answer:"Idag ska vi handla."},{words:["därför","måste","vi","lösa","problemet"],answer:"Därför måste vi lösa problemet."},{words:["i Finland","brukar","man","bada bastu","på lördagar"],answer:"I Finland brukar man bada bastu på lördagar."}]);return{id:"sentence-"+d.id,type:"order",skill:"Sentence",level:d.level,topic:d.topic,prompt:"Build the sentence. Remember V2 word order.",words:shuffle(e.words),answer:e.answer,explain:d.explanation}}
return{id:d.id,type:x.kind,skill:x.kind==="speaking"?"Speaking":"Writing",level:d.level,topic:d.topic,prompt:d.prompt,answer:null,explain:"Cover every requested part clearly. The next AI evaluation layer will assess open responses."}}
function render(){q=make({skill:$("skill").value,level:$("level").value,topic:$("topic").value});$("skillBadge").textContent=q.skill;$("levelBadge").textContent=q.level;$("counter").textContent=`Question ${session.done+1} / ${session.total}`;$("topicText").textContent=q.topic;$("prompt").textContent=q.prompt;$("feedback").innerHTML="";$("check").hidden=false;$("next").hidden=true;const b=$("body");b.innerHTML="";delete b.dataset.answer;
if(q.type==="choice"){const box=document.createElement("div");box.className="options";q.options.forEach(o=>{const el=document.createElement("button");el.className="option";el.textContent=o;el.onclick=()=>{document.querySelectorAll(".option").forEach(x=>x.classList.remove("selected"));el.classList.add("selected");b.dataset.answer=o};box.append(el)});b.append(box)}
else if(q.type==="text"){const i=document.createElement("input");i.className="answer";i.id="answer";i.placeholder="Type your answer…";b.append(i);i.focus()}
else if(q.type==="order"){const bank=document.createElement("div");bank.className="words";const preview=document.createElement("div");preview.className="preview";preview.textContent="Click words in order…";const chosen=[];q.words.forEach(w=>{const el=document.createElement("button");el.className="word";el.textContent=w;el.onclick=()=>{if(el.classList.contains("used"))return;el.classList.add("used");chosen.push(w);preview.textContent=chosen.join(" ");b.dataset.answer=chosen.join(" ")};bank.append(el)});b.append(bank,preview)}
else{const box=document.createElement("div");box.className="preview";box.textContent=q.skill==="Speaking"?"Speak for 60–90 seconds. Use PREP if useful.":"Write your response in Swedish and cover every task point.";const a=document.createElement("textarea");a.id="answer";a.rows=8;a.placeholder=q.skill==="Speaking"?"Optional notes…":"Write your Swedish response here…";b.append(box,a)}}
function show(ok,title,msg){$("feedback").className="feedback "+(ok?"good":"bad");$("feedback").innerHTML=`<strong>${title}</strong><br>${msg}`}
function check(){const answer=$("body").dataset.answer||$("answer")?.value||"";if(q.type==="speaking"||q.type==="writing"){if(answer.trim().length<10){show(false,"Add more","Please provide a longer response.");return}record(q.id,true);session.correct++;show(true,"Recorded","Open-response scoring will be added in the AI stage.")}else{const ok=norm(answer)===norm(q.answer);record(q.id,ok);if(ok)session.correct++;show(ok,ok?"Correct!":"Not quite",ok?q.explain:`Correct answer: ${q.answer}. ${q.explain}`)}session.done++;$("check").hidden=true;$("next").hidden=false;update()}
function update(){$("counter").textContent=`Question ${session.done} / ${session.total}`;$("totalCorrect").textContent=Object.values(progress).reduce((a,x)=>a+x.correct,0)+" correct";const weak=Object.entries(progress).sort((a,b)=>(a[1].correct/a[1].attempts)-(b[1].correct/b[1].attempts)).slice(0,6);$("weakness").innerHTML=weak.length?weak.map(([id,x])=>`<div><strong>${id}</strong><br><small>${Math.round(x.correct/x.attempts*100)}% · ${x.attempts} attempts</small></div>`).join(""):"<div>Start practicing and your weaker areas will appear here.</div>"}
$("check").onclick=check;$("next").onclick=()=>{if(session.done>=session.total)session={done:0,correct:0,total:10};render()};["skill","level","topic"].forEach(id=>$(id).onchange=()=>{session={done:0,correct:0,total:10};render()});$("reset").onclick=()=>{if(confirm("Reset local progress?")){progress={};localStorage.removeItem(KEY);session={done:0,correct:0,total:10};update();render()}};update();render();